# Generated by Django 2.1.5 on 2019-04-20 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fungo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genere', models.CharField(max_length=200)),
                ('specie', models.CharField(max_length=200)),
                ('autore', models.CharField(max_length=200)),
                ('var_f', models.CharField(max_length=200)),
                ('autore_var', models.CharField(max_length=200)),
                ('data_verifica', models.CharField(max_length=200)),
                ('comune_provincia', models.CharField(max_length=200)),
                ('localita', models.CharField(max_length=200)),
                ('Altezza_slm', models.CharField(max_length=200)),
                ('data', models.CharField(max_length=200)),
                ('principali_specie_vegetali', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=200)),
                ('tipologia_di_terreno', models.CharField(max_length=200)),
                ('raccolto_da_legit', models.CharField(max_length=200)),
                ('determinato_da_determinavit', models.CharField(max_length=200)),
                ('indicazione_cartografica_igm', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post'),
        ),
    ]
