# Generated by Django 2.1.5 on 2019-04-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('csv_file', models.FileField(upload_to='')),
            ],
        ),
    ]
