# Generated by Django 2.1.5 on 2019-04-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_fungo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fungo',
            name='genere',
            field=models.CharField(max_length=200),
        ),
    ]
